package license

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"
)

// Public key embedded in all tool binaries
// Generated by: go run cmd/keygen/main.go
const PublicKey = "pXiq+JTyG0atp8et+vG+5kFc8D6a2uCQcXf8Zs65nXk="

// ErrNotLicensed indicates no valid license found
var ErrNotLicensed = fmt.Errorf("not licensed")

// CheckEntitlement verifies license and tool access
// This is called by every tool on startup
func CheckEntitlement(toolName string) error {
	license, err := LoadLicense()
	if err != nil {
		return fmt.Errorf("%w: %v", ErrNotLicensed, err)
	}

	// Verify signature
	if err := Verify(*license, PublicKey); err != nil {
		return fmt.Errorf("license signature invalid: %w", err)
	}

	// Verify machine fingerprint
	currentFP, err := ComputeFingerprint()
	if err != nil {
		return fmt.Errorf("failed to compute fingerprint: %w", err)
	}

	if license.Payload.MachineFingerprint != currentFP {
		return fmt.Errorf("license is for a different machine")
	}

	// Check expiry
	if license.IsExpired() {
		if license.IsInGracePeriod() {
			// Warn but allow
			fmt.Fprintf(os.Stderr, "⚠️  License expired (grace period active)\n")
			fmt.Fprintf(os.Stderr, "   Run: nf-toolbox update\n\n")
		} else {
			return fmt.Errorf("license expired on %s", license.Payload.ExpiresAt.Format("Jan 2, 2006"))
		}
	}

	// Check entitlement
	if !license.HasAccess(toolName) {
		return fmt.Errorf("no license for %s", toolName)
	}

	return nil
}

// HasAccess checks if user owns a tool (for feature detection)
func HasAccess(toolName string) bool {
	license, err := LoadLicense()
	if err != nil {
		return false
	}
	return license.HasAccess(toolName)
}

// Verify checks license signature using public key
func Verify(license SignedLicense, publicKeyB64 string) error {
	// Decode public key
	pubKeyBytes, err := base64.StdEncoding.DecodeString(publicKeyB64)
	if err != nil {
		return fmt.Errorf("decode public key: %w", err)
	}
	publicKey := ed25519.PublicKey(pubKeyBytes)

	// Create canonical JSON
	canonical, err := canonicalJSON(license.Payload)
	if err != nil {
		return fmt.Errorf("canonical json: %w", err)
	}

	// Decode signature
	sig, err := base64.StdEncoding.DecodeString(license.Signature)
	if err != nil {
		return fmt.Errorf("decode signature: %w", err)
	}

	// Verify
	if !ed25519.Verify(publicKey, canonical, sig) {
		return fmt.Errorf("invalid signature")
	}

	return nil
}

// LoadLicense reads license from disk
func LoadLicense() (*SignedLicense, error) {
	path := getLicensePath()

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("license file not found")
	}

	var license SignedLicense
	if err := json.Unmarshal(data, &license); err != nil {
		return nil, fmt.Errorf("invalid license file")
	}

	return &license, nil
}

// SaveLicense writes license to disk
func SaveLicense(license *SignedLicense) error {
	path := getLicensePath()

	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}

	data, err := json.MarshalIndent(license, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(path, data, 0600)
}

// getLicensePath returns the license file path
func getLicensePath() string {
	return filepath.Join(GetConfigDir(), "license.json")
}

// GetConfigDir returns the config directory
func GetConfigDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".nf-tools", "config")
}

// GetBinDir returns the bin directory
func GetBinDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".nf-tools", "bin")
}

// GetCacheDir returns the cache directory
func GetCacheDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".nf-tools", "cache")
}

// canonicalJSON creates deterministic JSON for signature verification
func canonicalJSON(v interface{}) ([]byte, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}

	var m map[string]interface{}
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}

	return sortedMarshal(m)
}

func sortedMarshal(m map[string]interface{}) ([]byte, error) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	sorted := make([]byte, 0, 256)
	sorted = append(sorted, '{')

	for i, k := range keys {
		if i > 0 {
			sorted = append(sorted, ',')
		}

		keyBytes, _ := json.Marshal(k)
		sorted = append(sorted, keyBytes...)
		sorted = append(sorted, ':')

		valBytes, err := json.Marshal(m[k])
		if err != nil {
			return nil, err
		}
		sorted = append(sorted, valBytes...)
	}

	sorted = append(sorted, '}')
	return sorted, nil
}

// State tracks renewal attempts
type State struct {
	LastRenewAttempt time.Time `json:"last_renew_attempt"`
	LastRenewResult  string    `json:"last_renew_result"`
}

// LoadState reads state from disk
func LoadState() (*State, error) {
	path := filepath.Join(GetConfigDir(), "state.json")

	data, err := os.ReadFile(path)
	if err != nil {
		return &State{}, nil // Return empty state if not exists
	}

	var state State
	if err := json.Unmarshal(data, &state); err != nil {
		return &State{}, nil
	}

	return &state, nil
}

// SaveState writes state to disk
func SaveState(state *State) error {
	path := filepath.Join(GetConfigDir(), "state.json")

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}

	data, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(path, data, 0600)
}
